class Solution:
 def twoSum(s,n,t): # Class and method
     r=[x for x in n # construct a list of all numbers from `n` ...
    if t-x in set(n) # ... if t-x is also in `n` ...
    and t-x!=x] # ... and they aren't the same value ...
     or[t//2,t//2]; # ... or, if there's no such numbers, return the mean 2x
     return [i for i,x in enumerate(n)if x in r] # iterate over the numbers we chose, and make a new list containing their indices
